### ISSUE TITLE
load_db_from_file ValueError - level must be >= 0

### ISSUE THREAD

**Issue by lucasduffey** [nccgroup/umap2#15]
```
user@hostname:~/research/umap2$ sudo umap2vsscan -P fd:/dev/ttyUSB0 -d data/vid_pid_db.py
[ALWAYS] Resume file not found. Creating new one
[INFO  ] loading vid_pid db file: data/vid_pid_db.py
Traceback (most recent call last):
  File "/usr/local/bin/umap2vsscan", line 9, in <module>
    load_entry_point('umap2', 'console_scripts', 'umap2vsscan')()
  File "/home/user/research/umap2/umap2/apps/vsscan.py", line 304, in main
    app.run()
  File "/home/user/research/umap2/umap2/apps/vsscan.py", line 223, in run
    self.build_scan_session()
  File "/home/user/research/umap2/umap2/apps/vsscan.py", line 191, in build_scan_session
    self.load_db_from_file(db_file)
  File "/home/user/research/umap2/umap2/apps/vsscan.py", line 152, in load_db_from_file
    module = __import__(modulename, globals(), locals(), [], -1)
ValueError: level must be >= 0
```

**Comment by lucasduffey** [comment]
just realized it might be my problem, closing until I verify

**Comment by HAblueHA** [comment]
@lucasduffey, I have currently the same problem, I have no clue what could be wrong, can you pls assist me (7 years later...)
