### ISSUE TITLE
umap2kitty ImportError: No module named 'templates'

### ISSUE THREAD

**Issue by elouet** [nccgroup/umap2#28]
I'm struggling with the set-up of my umap2. There seems to be a mix of python2 and python3 that's causing all sorts of issues (some PR to follow...). 

At the moment I try to follow the fuzzing instructions from the main README. 

```
$ umap2kitty -s ~/Tools/umap2/umap2/fuzz/templates/mass_storage.stages 
Traceback (most recent call last):
  File "/usr/local/bin/umap2kitty", line 9, in <module>
    load_entry_point('umap2==2.0.1', 'console_scripts', 'umap2kitty')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/umap2-2.0.1-py3.5.egg/umap2/fuzz/fuzz_engine.py", line 23, in <module>
ImportError: No module named 'templates'

```

Not sure how to fix this, maybe using PYTHONPATH but it seems to have averse side effects.

**Comment by elouet** [comment]
The error is gone after I set python2 as default in update-alternatives.
