### ISSUE TITLE
support greatfet?

### ISSUE THREAD

**Issue by shtry** [nccgroup/umap2#31]
Hi.

Does umap2 tool support greatfet?

I get a device error as below.

```
$ sudo umap2emulate -P fd:/dev/ttyUSB0 -C fidi
[INFO  ] Loading physical interface: fd:/dev/ttyUSB0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/umap2emulate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/umap2/apps/emulate.py", line 53, in main
    app.run()
  File "/usr/local/lib/python3.8/dist-packages/umap2/apps/emulate.py", line 35, in run
    self.phy = self.load_phy(self.options['--phy'])
  File "/usr/local/lib/python3.8/dist-packages/umap2/apps/base.py", line 66, in load_phy
    s = Serial(dev_name, 115200, parity=PARITY_NONE, timeout=2)
  File "/usr/local/lib/python3.8/dist-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
```

**Comment by BinyaminSharet** [comment]
Never tested that, but it seems the the exception is raised because there's no /dev/ttyUSB0 device

**Comment by shtry** [comment]
Wow. I wanted to see you. @BinyaminSharet 

What does "/dev/ttyUSB0" mean?

I think the Facedancer hardware is connected to "/dev/ttyUSB0" when connected.

The "GreatFET" hardware is not connected to that device("/dev/ttyUSB0").

Hmm.. Is there a solution?

The "GreatFET" hardware runs the Facedancer source well.

**Comment by shtry** [comment]
I thought this was closed because it was quiet.

But I'm very happy to see your comments.

**Comment by BinyaminSharet** [comment]
`/dev/ttyUSB0` is the filesystem access to the usb device. You can check what interfaces you can access by running `ls /dev/`
The interface name of the greatfet might change (based on other devices that are connected) you can probably see it in the system log (dmesg) when you connect the greatfet to your computer.

**Comment by shtry** [comment]
Exactly, the device "/dev/ttyUSB0" could not be found.

As you advised, I will try again.

**Comment by shtry** [comment]
Hi. @BinyaminSharet 

dmesg log:
```

[ 2479.728357] usb 1-1: new high-speed USB device number 6 using xhci_hcd
[ 2479.877163] usb 1-1: New USB device found, idVendor=1c20, idProduct=40e5, bcdDevice= 1.00
[ 2479.877167] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2479.877171] usb 1-1: Product: GreatFET
[ 2479.877173] usb 1-1: Manufacturer: Great Scott Gadgets
[ 2479.877175] usb 1-1: SerialNumber: 00000000000000000007777578

$ dmesg | grep tty
[    0.178785] printk: console [tty0] enabled
```

**Comment by shtry** [comment]
Does the "/dev/ttyUSB0" device point to the target?

Or the host?

**Comment by BinyaminSharet** [comment]
No, but if the example works well, take a look on how they connect to the device there. I've never worked with it.

**Comment by shtry** [comment]
Okay, Very Thank you!

**Comment by tronchama** [comment]
Hi.

I'm trying to use GreatFET and umap2 but I'm having the same problem. GreatFET is not going to be mapped to any TTY because it's not a serial device. I was wondering how @shtry managed to get it to work (if it even worked at all) and how should I proceed to work with it, since the connection to the device using Facedancer is not done via serial. 
Should I open a new issue for this? 

dmesg and error logs are relatively similar to the ones @shtry posted before. I can see a /dev/greatfet-oneX-X created but, as expected, it gives an error if I try to use it.

```
$ umap2scan -P fd:/dev/greatfet-one1-2 
[ALWAYS] Scanning host for supported devices
[INFO  ] Loading physical interface: fd:/dev/greatfet-one1-2
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 398, in _reconfigure_port
    orig_attr = termios.tcgetattr(self.fd)
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v/.local/bin/umap2scan", line 8, in <module>
    sys.exit(main())
  File "/home/v/.local/lib/python3.8/site-packages/umap2/apps/scan.py", line 80, in main
    app.run()
  File "/home/v/.local/lib/python3.8/site-packages/umap2/apps/scan.py", line 42, in run
    phy = self.load_phy(self.options['--phy'])
  File "/home/v/.local/lib/python3.8/site-packages/umap2/apps/base.py", line 66, in load_phy
    s = Serial(dev_name, 115200, parity=PARITY_NONE, timeout=2)
  File "/usr/local/lib/python3.8/dist-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 332, in open
    self._reconfigure_port(force_update=True)
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 401, in _reconfigure_port
    raise SerialException("Could not configure port: {}".format(msg))
serial.serialutil.SerialException: Could not configure port: (25, 'Inappropriate ioctl for device')
```
Thanks in advance.
