### ISSUE TITLE
does it support for cynthion hardware  with facdancer?

### ISSUE THREAD

**Issue by mcblog** [nccgroup/umap2#39]
I try to use it on Cynthion board, use fuzz mode,but failed.
this is my step
1、`cynthion run facedancer`
2、`lsusb`  to show id
3、`modprobe option`
4、`sh -c 'echo "1d50 615b" >/sys/bus/usb-serial/drivers/option1/new_id'`
then run it. on /dev/ttyUSB0
but show this:
```
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
[WARNING ][controller.do] still waiting for umap_stack to remove the file /tmp/umap_kitty/trigger_disconnect
^C[INFO    ][client.stop] Stopping client fuzzer
Failed to stop thread
```

```
[INFO  ] Loading physical interface: fd:/dev/ttyUSB0
[INFO  ] Facedancer resetting...
Traceback (most recent call last):
  File "/usr/local/bin/umap2emulate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/umap2/apps/emulate.py", line 53, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/umap2/apps/emulate.py", line 35, in run
    self.phy = self.load_phy(self.options['--phy'])
  File "/usr/local/lib/python2.7/dist-packages/umap2/apps/base.py", line 68, in load_phy
    phy = Max342xPhy(self, s)
  File "/usr/local/lib/python2.7/dist-packages/umap2/phy/facedancer/max342x_phy.py", line 73, in __init__
    self.device = Facedancer(serial_port)
  File "/usr/local/lib/python2.7/dist-packages/umap2/phy/facedancer/facedancer.py", line 14, in __init__
    self.reset()
  File "/usr/local/lib/python2.7/dist-packages/umap2/phy/facedancer/facedancer.py", line 23, in reset
    self.halt()
  File "/usr/local/lib/python2.7/dist-packages/umap2/phy/facedancer/facedancer.py", line 17, in halt
    self.serialport.setRTS(1)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 600, in setRTS
    self.rts = value
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 463, in rts
    self._update_rts_state()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 706, in _update_rts_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_RTS_str)
IOError: [Errno 110] Connection timed out

```

it show that timed out. any other solutions?

**Comment by BinyaminSharet** [comment]
Support for this board was not added, nor tested, you are welcome to add support and open a relevant pull request for this, as I don't have a board to develop/test it on.
However, better logs (syslog etc.) and OS information might be helpful, along with the exact commands that you executed.

**Comment by DeveloperMarius** [comment]
Hello @mcblog,
If your are still looking for a way to use umap2 with your Cynthion hardware, I opened a PR #41 that allows the use of the Cynthion for umap2.
Just follow the [documentation](https://cynthion.readthedocs.io/en/latest/getting_started_facedancer.html) on how to use Facedancer with Cynthion and then use umap2 with the `-P cynthion` argument.

~ Marius
